[package]
name = "indy-utils"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

description = "This is the official SDK for Hyperledger Indy (https://www.hyperledger.org/projects), which provides a distributed-ledger-based foundation for self-sovereign identity (https://sovrin.org). The major artifact of the SDK is a c-callable library."
license = "MIT/Apache-2.0"

[lib]
name = "indy_utils"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["base58", "ed25519", "hash", "wql"]
base58 = ["bs58"]
ed25519 = ["ursa/ed25519", "ursa/x25519"]
hash = ["ursa/sha2"]
serde-serialize = ["serde", "serde_derive", "serde_json"]
wql = ["serde-serialize"]

[dependencies]
base64 = "0.10.1"
bs58 = { version = "0.3.0", optional = true }
hex = "0.4.0"
lazy_static = "1.3.0"
regex = "1.3.1"
serde = { version = "1.0.106", optional = true }
serde_derive = { version = "1.0.106", optional = true }
serde_json = { version = "1.0.40", optional = true }
tempfile = { version = "3.1.0", optional = true }

[dependencies.ursa]
version = "0.3.2"
default-features = false

[dev-dependencies]
rand = "0.7.2"
