[package]
name = "indy-data-types"
version = "0.1.0"
authors = ["Hyperledger Indy Contributors <hyperledger-indy@lists.hyperledger.org>"]
edition = "2018"

description = "This is the official SDK for Hyperledger Indy (https://www.hyperledger.org/projects), which provides a distributed-ledger-based foundation for self-sovereign identity (https://sovrin.org). The major artifact of the SDK is a c-callable library."
license = "MIT/Apache-2.0"

[lib]
name = "indy_data_types"
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["serde-serialize"]
serde-serialize = ["indy-utils/serde-serialize", "serde", "serde_derive", "serde_json"]

[dependencies]
lazy_static = "1.3.0"
regex = "1.3.1"
serde = { version = "1.0.106", optional = true }
serde_derive = { version = "1.0.106", optional = true }
serde_json = { version = "1.0.50", optional = true }
indy-utils = { path = "../indy-utils", features = ["cl"] }

[dev-dependencies]
hex = "0.4.0"
serde_json = "1.0.50"
