name: "Run Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test Suite

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v1

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Debug build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets

      - name: Test default features
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Test CL
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path indy-data-types/Cargo.toml --features cl

      - name: Test CL-native
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path indy-data-types/Cargo.toml --features cl_native
